### PR TITLE
Forms project, copying the Mint Sign Up formm

### PR DESCRIPTION
**Pull request by lmaldonadoch**
In this project, we worked on the understanding of how forms work and how to style them. We were able to add all the elements and aesthetic features shown on the website.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
### Hi @lmaldonadoch and @shubhsk88 
### You have done a great job 💪  the page looks almost like the original. However, some requirements are still missing in the implementation of your project.

**_1. Enable linter for this Pull Request( in other words, make sure that stickler is working)_**

**_2. Fix the 'Value Error' in the style.css file_**

image

**_3. The email should have an `<input>` of type `email` and a label `Email address`_** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))

**_4. The phone should have an `<input>` of type `tel` and a label `Phone`_** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))

### Note: Try to add the live demo link to the readme file

**_Implement the changes and submit for review_**

**_If you have doubt or questions contact me on slack_**

### Reviewed by: _Temitayo Adeleke_

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes

**Comment by lmaldonadoch** [comment]
Thanks for the comments! We have corrected the mentioned details.

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi **TEAM**, you have done a great job in implementing the requested changes by the previous TSE 👍 
The project is really good and now meets the minimum requirements 😄 Go ahead and merge to master and submit the project completion form. Congratulations 🍰 

Good luck with your next project ✋ 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo

**Pull request merged**
